# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/cancunf-motcamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/cancunf-motcamera


PRODUCT_PACKAGES += \
    MotoSignatureApp \
    MotCamera3AI \
    MotCamera4 \
    MotorolaSettingsProvider \
    com.motorola.motosignature \
    moto-core_services \
    moto-settings \
    com.motorola.motosignature \
    moto-core_services \
    moto-settings \
    com.motorola.camera3.cancunf \
    com.motorola.camera3.content.ai \
    com.motorola.camera3.lens \
    com.motorola.camera3 \
    com.motorola.moto-uirefresh \
    deviceowner-configuration-com.motorola.camera3 \
    privapp-permissions-com.motorola.camera3 \
    hiddenapi-whitelist-com.motorola.camera3 \
    motsettings
