# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/cancunf-motcamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/cancunf-motcamera


PRODUCT_PACKAGES += \
    MotoSignatureApp \
    MotCamera3AI \
    MotCamera4 \
    MotorolaSettingsProvider \
    com.motorola.motosignature \
    moto-core_services \
    moto-settings \
    com.motorola.motosignature.xml \
    moto-core_services.xml \
    moto-settings.xml \
    com.motorola.camera3.cancunf.xml \
    com.motorola.camera3.content.ai.xml \
    com.motorola.camera3.lens.xml \
    com.motorola.camera3.xml \
    com.motorola.moto-uirefresh.xml \
    deviceowner-configuration-com.motorola.camera3.xml \
    privapp-permissions-com.motorola.camera3.xml \
    hiddenapi-whitelist-com.motorola.camera3.xml \
    motsettings
